### ISSUE TITLE
Error when compiling grammar with inheritence

### ISSUE THREAD

**Issue by fpom** [lisael/fastidious#1]
Dear Lisael,

I'm trying to use fastidious in a project of mine, and I'm particularly interested in its ability to generate code with no external dependencies. But when I'm trying to compile a grammar defined from multiple classes, I get an error:

```
$ python3 -m fastidious generate bug.ExpressionParser
[snip]
AttributeError: 'MemoizedExpr' object has no attribute 'is_syntaxic_terminal'
```

Here is file `bug.py` that triggers this error:

```python
import fastidious

class ExpressionParser (fastidious.Parser) :
    __default__ = "INPUT"

    __grammar__ = r"""
    INPUT <- :expr EOF {@expr}
    EOF   <- !.
    _     <- [\t ]*
    """
    def on__ (self, value) :
        return ""

    __grammar__ += """
    NUMBER <- [+-]? _ [0-9]+
    """
    def on_NUMBER (self, value) :
        return int(self.p_flatten(value))

    __grammar__ += r"""
    expr <- first:term rest:([+-] term)*
    term <- first:fact rest:([*/] fact)* {on_expr}
    fact <- (_ "(" fact:expr ")" _) / fact:atom {@fact}
    atom <- _ value:NUMBER _ {@value}
    """
    def on_expr (self, value, first, rest) :
        expr = first
        for op, tr in rest :
            expr = (op, expr, tr)
        return expr

class VarExprParser (ExpressionParser) :
    __default__ = "INPUT"

    __grammar__ = r"""
    atom <- _ value:(NUMBER / NAME) _ {@value}
    NAME <- [a-z]i ([a-z0-9_]i)*
    """
    def on_NAME (self, value) :
        return self.p_flatten(value)
```

The same error occurs if I try to generate code for `VarExprParser`, but it vanishes if I remove this class.

Thanks in advance for your help!

Cheers,
Franck

**Comment by lisael** [comment]
Sorry, it's been a long time I somewhat abandoned fastidious (and my email notifications, somehow I didn't see this issue at the time.). It was sort-of-working-enough for my own needs. I'm currently on a new project using fastidious, and it should improve dramatically and reach the 1.0 version in the next months.

That said, the memoization stuff is a late addition that is half baked and breaks a lot of parts in fastidious. I'm to remove it altogether at the moment.

I doubt that you're still using fastidious, but well... I'll let you know when it's fixed.

Again, sorry for the lack of reactivity. I write stuff without even hoping someone else use it, too often.

**Comment by fpom** [comment]
No problem for your latency, I understand this very much.  ;)

I actually still use fastidious, with samll changes to adapt it to my particular needs. I'd be happy to use a new version when it'll be available. What I appreciate in particular is the ability to generate parsers that do not rely on any runtime library, so I can distributes them within my tools without adding any dependency.

Regarding my report, I've worked around avoiding to subclass parsers.

**Comment by lisael** [comment]
Nice. I read your changes, and I'll do my best to merge them back into fastidious. Thank you for using Fastidious. I'm currently fixing a bunch of small annoying issues, and when in good shape, I plan to release v0.2.0. At that point, either we can merge your branch directly or I try to make fastious compatible with it.

**Comment by fpom** [comment]
I'm glad you like my changes. But note that I did not intend them to be general. It's more a bunch of ad-hoc features I wanted to have for my own use.
